/**
 * Mock inbox documents for the Inbox View Dashboard
 */

export type InboxDocument = {
  id: string;
  filename: string;
  clientId: string;
  clientName: string;
  periodId: string;
  periodName: string;
  documentType: "invoice" | "receipt" | "bill" | "bank_statement" | "other";
  status: "processing" | "clean" | "needs_review" | "quarantined";
  approvalStatus: "pending" | "approved" | "rejected" | "flagged";
  uploadedAt: string;
  uploaderName: string;
  extracted?: {
    vendor?: string;
    amount?: number;
    date?: string;
    invoiceNumber?: string;
  };
  periodRequestId?: string | null;
  flags?: string[];
};

export const mockInboxDocuments: InboxDocument[] = [
  {
    id: "doc-1",
    filename: "Invoice_ABC_Corp_Oct2025.pdf",
    clientId: "client-1",
    clientName: "Vance Industries",
    periodId: "period-1",
    periodName: "2025-10",
    documentType: "invoice",
    status: "clean",
    approvalStatus: "pending",
    uploadedAt: "2025-10-23T10:30:00Z",
    uploaderName: "John Vance",
    extracted: {
      vendor: "ABC Corp",
      amount: 2450.0,
      date: "2025-10-15",
      invoiceNumber: "INV-2025-1234",
    },
  },
  {
    id: "doc-2",
    filename: "Office_Supplies_Receipt.pdf",
    clientId: "client-1",
    clientName: "Vance Industries",
    periodId: "period-1",
    periodName: "2025-10",
    documentType: "receipt",
    status: "clean",
    approvalStatus: "pending",
    uploadedAt: "2025-10-23T09:15:00Z",
    uploaderName: "Sarah Johnson",
    extracted: {
      vendor: "Office Depot",
      amount: 125.5,
      date: "2025-10-14",
    },
  },
  {
    id: "doc-3",
    filename: "Bank_Statement_October.pdf",
    clientId: "client-2",
    clientName: "Cole Logistics",
    periodId: "period-3",
    periodName: "2025-10",
    documentType: "bank_statement",
    status: "clean",
    approvalStatus: "pending",
    uploadedAt: "2025-10-23T08:45:00Z",
    uploaderName: "Michael Cole",
    extracted: {
      vendor: "Chase Bank",
      amount: 15234.0,
      date: "2025-10-01",
    },
  },
  {
    id: "doc-4",
    filename: "Amazon_Receipt_Electronics.pdf",
    clientId: "client-1",
    clientName: "Vance Industries",
    periodId: "period-1",
    periodName: "2025-10",
    documentType: "receipt",
    status: "clean",
    approvalStatus: "approved",
    uploadedAt: "2025-10-22T16:20:00Z",
    uploaderName: "John Vance",
    extracted: {
      vendor: "Amazon",
      amount: 89.99,
      date: "2025-10-12",
    },
  },
  {
    id: "doc-5",
    filename: "Utility_Bill_October.pdf",
    clientId: "client-3",
    clientName: "Rossi & Co.",
    periodId: "period-5",
    periodName: "2025-10",
    documentType: "bill",
    status: "clean",
    approvalStatus: "flagged",
    uploadedAt: "2025-10-22T14:00:00Z",
    uploaderName: "Maria Rossi",
    extracted: {
      vendor: "Pacific Gas & Electric",
      amount: 456.78,
      date: "2025-10-05",
    },
    flags: ["Amount unusually high"],
  },
  {
    id: "doc-6",
    filename: "Consultant_Invoice.pdf",
    clientId: "client-2",
    clientName: "Cole Logistics",
    periodId: "period-3",
    periodName: "2025-10",
    documentType: "invoice",
    status: "needs_review",
    approvalStatus: "pending",
    uploadedAt: "2025-10-22T11:30:00Z",
    uploaderName: "Michael Cole",
    extracted: {
      vendor: "Tech Consulting Inc",
      amount: 5000.0,
      date: "2025-10-10",
      invoiceNumber: "CONS-789",
    },
    flags: ["Missing purchase order"],
  },
  {
    id: "doc-7",
    filename: "Receipt_Parking.jpg",
    clientId: "client-1",
    clientName: "Vance Industries",
    periodId: "period-1",
    periodName: "2025-10",
    documentType: "receipt",
    status: "clean",
    approvalStatus: "pending",
    uploadedAt: "2025-10-21T17:45:00Z",
    uploaderName: "Sarah Johnson",
    extracted: {
      vendor: "Downtown Parking",
      amount: 25.0,
      date: "2025-10-21",
    },
  },
  {
    id: "doc-8",
    filename: "Insurance_Invoice_Q4.pdf",
    clientId: "client-3",
    clientName: "Rossi & Co.",
    periodId: "period-5",
    periodName: "2025-10",
    documentType: "invoice",
    status: "clean",
    approvalStatus: "approved",
    uploadedAt: "2025-10-21T10:00:00Z",
    uploaderName: "Maria Rossi",
    extracted: {
      vendor: "State Farm Insurance",
      amount: 1200.0,
      date: "2025-10-01",
      invoiceNumber: "INS-Q4-2025",
    },
  },
  {
    id: "doc-9",
    filename: "Marketing_Services_Bill.pdf",
    clientId: "client-4",
    clientName: "Thompson & Associates",
    periodId: "period-8",
    periodName: "2025-10",
    documentType: "bill",
    status: "clean",
    approvalStatus: "pending",
    uploadedAt: "2025-10-20T15:30:00Z",
    uploaderName: "Robert Thompson",
    extracted: {
      vendor: "Digital Marketing Pro",
      amount: 850.0,
      date: "2025-10-15",
    },
  },
  {
    id: "doc-10",
    filename: "Travel_Receipt_Hotel.pdf",
    clientId: "client-2",
    clientName: "Cole Logistics",
    periodId: "period-3",
    periodName: "2025-10",
    documentType: "receipt",
    status: "clean",
    approvalStatus: "rejected",
    uploadedAt: "2025-10-20T09:00:00Z",
    uploaderName: "Michael Cole",
    extracted: {
      vendor: "Marriott Hotel",
      amount: 320.0,
      date: "2025-10-08",
    },
  },
  {
    id: "doc-11",
    filename: "Software_Subscription_Inv.pdf",
    clientId: "client-1",
    clientName: "Vance Industries",
    periodId: "period-1",
    periodName: "2025-10",
    documentType: "invoice",
    status: "processing",
    approvalStatus: "pending",
    uploadedAt: "2025-10-23T11:00:00Z",
    uploaderName: "John Vance",
  },
  {
    id: "doc-12",
    filename: "Legal_Fees_Invoice.pdf",
    clientId: "client-5",
    clientName: "Garcia Manufacturing",
    periodId: "period-9",
    periodName: "2025-10",
    documentType: "invoice",
    status: "clean",
    approvalStatus: "pending",
    uploadedAt: "2025-10-19T14:20:00Z",
    uploaderName: "Carlos Garcia",
    extracted: {
      vendor: "Smith & Partners Law",
      amount: 3500.0,
      date: "2025-10-01",
      invoiceNumber: "LEGAL-2025-456",
    },
  },
  {
    id: "doc-13",
    filename: "Office_Rent_October.pdf",
    clientId: "client-3",
    clientName: "Rossi & Co.",
    periodId: "period-5",
    periodName: "2025-10",
    documentType: "invoice",
    status: "clean",
    approvalStatus: "approved",
    uploadedAt: "2025-10-19T08:00:00Z",
    uploaderName: "Maria Rossi",
    extracted: {
      vendor: "Downtown Properties LLC",
      amount: 2800.0,
      date: "2025-10-01",
      invoiceNumber: "RENT-10-2025",
    },
  },
  {
    id: "doc-14",
    filename: "Shipping_Invoice_FedEx.pdf",
    clientId: "client-2",
    clientName: "Cole Logistics",
    periodId: "period-3",
    periodName: "2025-10",
    documentType: "invoice",
    status: "clean",
    approvalStatus: "pending",
    uploadedAt: "2025-10-18T16:00:00Z",
    uploaderName: "Michael Cole",
    extracted: {
      vendor: "FedEx",
      amount: 145.67,
      date: "2025-10-15",
      invoiceNumber: "FX-2025-9876",
    },
  },
  {
    id: "doc-15",
    filename: "Equipment_Repair_Bill.pdf",
    clientId: "client-5",
    clientName: "Garcia Manufacturing",
    periodId: "period-9",
    periodName: "2025-10",
    documentType: "bill",
    status: "needs_review",
    approvalStatus: "pending",
    uploadedAt: "2025-10-18T10:30:00Z",
    uploaderName: "Carlos Garcia",
    extracted: {
      vendor: "Industrial Repairs Inc",
      amount: 780.0,
      date: "2025-10-12",
    },
    flags: ["Missing approval signature"],
  },
];
